hospital/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
hospital/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/HospitalOperatingHoursExceptionType.java
hospital/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalListResDto.java
hospital/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/domain/HospitalOperatingHours.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/dto/HospitalOperatingHoursReqDto.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/dto/HospitalOperatingHoursResDto.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/repository/HospitalOperatingHoursRepository.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/service/HospitalOperatingHoursService.java

- 병원영업시간 추가, 조회, 수정, 삭제 api 구현
---
---
---
병원 영업시간 id3번 deletedAt에 현재 시간 찍힘
---
dayOfWeek(요일)을 엔티티에서 '@Enumerated(EnumType.STRING)' 어노테이션을 붙여줬음에도 불구하고 DB상에는 dayOfWeek 데이터 타입이 int로 되어있어서 안들어가지는 오류 발생 
-> 임의로 DB에서 직접 데이터 형식을 string으로 modify 해줬더니 되긴 됨. 이거 다시 살펴봐야할 것 같음
feat/IS-18

feat/IS-18 : 병원영업시간 추가, 조회, 수정, 삭제 api 구현

---

member/build.gradle
member/src/main/java/com/padaks/todaktodak/MemberApplication.java
member/src/main/java/com/padaks/todaktodak/common/dto/CommonResDto.java
member/src/main/java/com/padaks/todaktodak/config/JwtAuthFilter.java
member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberUpdateReqDto.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

회원가입 및 회원 수정에서 이미지 업로드와 수정 가능하도록 설정
단, 이미지 업로드는 form-data형식이라 address는 테스가 불가. JSON에서만 가능하니 테스트에는 주소 빼시고 부탁드립니다
- 회원가입 이미지
- 정보 수정 이미지
feat/IS-21

feat: 회원 이미지 업로드 -> 회원가입, 내 정보 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationReqDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
reservation/src/test/java/com/padaks/todaktodak/ReservationListTest.java

병원별 예약 list 출력 API 구현
1. 유저별 조회
2. 의사별 조회
3. 예약 상태별 조회

#23 feat : 병원 예약 list 출력 기능 구현

---

member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
member/src/main/java/com/padaks/todaktodak/child/dto/ChildRegisterResDto.java
member/src/main/java/com/padaks/todaktodak/child/dto/ChildResDto.java
member/src/main/java/com/padaks/todaktodak/child/dto/ChildShareReqDto.java
member/src/main/java/com/padaks/todaktodak/child/repository/ChildRepository.java
member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
member/src/main/java/com/padaks/todaktodak/childparentsrelationship/repository/ChildParentsRelationshipRepository.java
member/src/main/java/com/padaks/todaktodak/childparentsrelationship/service/ChildParentsRelationshipService.java
member/src/main/java/com/padaks/todaktodak/common/service/AESUtil.java

- 자녀 공유 기능 추가
- 자녀 주민번호 암호화
- 자녀 공유 기능 추가
1번 자녀를 3번 회원에게 공유하게 되면 1-3 자녀-부모관계 생성된다
- 자녀 주민번호 암호화
데이터베이스에서 암호화해서 넣고 조회할때 다시 복호화한다
Feat/is 15

Feat/is 15: 자녀 공유 기능 & 주민번호 암호화

---

hospital/build.gradle
hospital/src/main/java/com/padaks/todaktodak/HospitalApplication.java
hospital/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
hospital/src/main/java/com/padaks/todaktodak/common/dto/CommonErrorDto.java
hospital/src/main/java/com/padaks/todaktodak/configs/JwtAuthFilter.java
hospital/src/main/java/com/padaks/todaktodak/configs/JwtTokenProvider.java
hospital/src/main/java/com/padaks/todaktodak/configs/RedisConfig.java
hospital/src/main/java/com/padaks/todaktodak/configs/SecurityConfig.java
hospital/src/main/java/com/padaks/todaktodak/doctor/controller/DoctorController.java
hospital/src/main/java/com/padaks/todaktodak/doctor/domain/Doctor.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/DoctorDetailDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/DoctorListDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/DoctorLoginDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/DoctorSaveDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/DoctorUpdateDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/dto/EmailVerificationDto.java
hospital/src/main/java/com/padaks/todaktodak/doctor/repository/DoctorRepository.java
hospital/src/main/java/com/padaks/todaktodak/doctor/service/CustomDoctorDetailsService.java
hospital/src/main/java/com/padaks/todaktodak/doctor/service/DoctorService.java
hospital/src/main/java/com/padaks/todaktodak/doctor/service/JavaEmailService.java
hospital/src/main/java/com/padaks/todaktodak/doctor/service/RedisService.java
member/src/main/java/com/padaks/todaktodak/MemberApplication.java
member/src/main/java/com/padaks/todaktodak/config/JwtAuthFilter.java
member/src/main/java/com/padaks/todaktodak/config/JwtTokenProvider.java
member/src/main/java/com/padaks/todaktodak/config/SecurityConfig.java
member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

- 의사 회원가입 및 이메일 인증
토큰 검증 및 발급, 순환참조 이슈 해결 
자바 라이브러리를 활용한 이메일 인증 서비스
- 의사 로그인
- 의사 회원탈퇴 기능  
- 이메일 인증
- 회원가입
- 로그인
- 탈퇴
feat/IS-28

feat: 의사 화원가입, 로그인, 이메일 인증, 탈퇴 

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/UpdateStatusReservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

예약 상태 변경 API 작성
1. Completed
2. Noshow
1.
2.

Feat/is 29 예약 상태 수정 API 기능 구현

---

reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/common/dto/CommonErrorDto.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/CommonResDto.java
reservation/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/ReservationExceptionType.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/controller/MedicalChartController.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartResDto.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/repository/MedicalChartRepository.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartFeign.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

- 진료 내역 등록 기능
- 진료 내역 조회 기능
feign 연결 전입니달라

Feat/is 24 진료 내역 등록/조회 API

---

Dockerfile

chore: 서버 배포 2차 테스트

---

Dockerfile

chore: 서버 배포 3차 테스트

---

Dockerfile

chore: 서버 배포 4차 테스트

---

Dockerfile

chore: 서버 배포 5차 테스트

---

Dockerfile

chore: 서버 배포 6차 테스트

---

reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

Fix : 예약 상태 변경 코드 수정

---

Dockerfile

chore: 서버 배포 7차 테스트

---

Dockerfile

[//]: # (ex&#41;  feat/IS-1)\
feat/IS-31

chore: 서버 배포 8차 테스트

---

hospital/src/main/java/com/padaks/todaktodak/doctor/domain/Doctor.java
hospital/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
hospital/src/main/java/com/padaks/todaktodak/hospital/domain/Hospital.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalDetailResDto.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalRegisterReqDto.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalUpdateReqDto.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalUpdateResDto.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/domain/HospitalOperatingHours.java

- hospital 엔티티 필드 추가 후 병원DTO 관련 코드 수정
###포스트맨
feat/IS-22

Feat/IS-22 : hospital 엔티티 필드 추가 후 병원DTO 관련 코드 수정

---

community/build.gradle
community/src/main/java/com/padaks/todaktodak/config/AwsS3Configs.java
community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostListDto.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostsaveDto.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
community/src/main/java/com/padaks/todaktodak/util/S3ClientFileUpload.java

Post 등록 기능 추가
db에 저장 확인
feat/IS-27

IS-27 feat: Post 등록

---

reservation/src/main/java/com/padaks/todaktodak/medicalchart/controller/MedicalChartController.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/domain/MedicalChart.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartResDto.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/dto/MedicalChartSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java

- MedicalChart 엔티티 수정 및 상태변경 로직 추가
Feat/is-30

Feat/is-30: fix: MedicalChart 엔티티 수정 및 상태변경 로직 추가

---

.github/workflows/deploy-server-with-compose.yml
.gitignore
member/.gitignore

chore: 서버 배포 9차 테스트

---

Dockerfile

chore: 서버 배포 10차 테스트

---

.github/workflows/deploy-server-with-compose.yml
Dockerfile

chore: 서버 배포 11차 테스트

---

.github/workflows/deploy-server-with-compose.yml

chore: 서버 배포 12차 테스트

---

member/src/main/resources/application.yml

chore: 서버 배포 13차 테스트

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java

chore: 서버 배포 16차 테스트

---

member/src/main/resources/application.yml

chore: 서버 배포 17차 테스트

---

member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

chore: 서버 배포 18차 테스트

---

member/Dockerfile

chore: 서버 배포 19차 테스트

---

.github/workflows/deploy-server-with-compose.yml

chore: 서버 배포 20차 테스트

---

.github/workflows/deploy-server-with-compose.yml
reservation/.gitignore
reservation/Dockerfile

chore: reservation 개발 서버 배포 1차

---

member/src/main/resources/application.yml

chore: reservation 개발 서버 배포 2차

---

reservation/src/main/resources/application.yml

chore: reservation 개발 서버 배포 3차

---

reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java

chore: reservation 개발 서버 배포 4차

---

reservation/src/main/java/com/padaks/todaktodak/common/controller/CommonController.java

chore: reservation 개발 서버 배포 5차

---

community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
community/src/main/java/com/padaks/todaktodak/comment/repository/CommentRepository.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostListDto.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostUpdateReqDto.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostsaveDto.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java

게시글 상세내역 조회
게시글 업데이트
게시글 상세조회
게시글 업데이트
db 변경 사항 - 수정 전
db 변경 사항 - 수정 후
짜잘한 수정내용 1
- comment 수정내용
실행에는 문제가 없지만
@Builder.Default. If it is not supposed to be settable during building, make the field final. private List<Notification> communityNotificationList = new ArrayList<>(); 이렇게 에러가 생김!
에러 내용 : 필드에 초기값을 할당했지만, @Builder가 이 초기값을 무시한다
에러 해결 : @Builder.Default 추가
- 필드의 초기값을 빌더가 사용할 수 있도록 하려면, 각 필드에 @Builder.Default 애너테이션을 추가합니다. (라는 참고를 보고 수정..)
짜잘한 수정내용 2
 postDetail에서 comment detail 나타나야해서 comment 수정.. 
IS-33

Feat/IS-33 feat : 게시글 detail 조회, 게시글 update

---

reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java
reservation/src/main/java/com/padaks/todaktodak/configs/CorsConfig.java
reservation/src/main/java/com/padaks/todaktodak/untact/config/WebSocketConfig.java
reservation/src/main/java/com/padaks/todaktodak/untact/controller/UntactController.java
reservation/src/main/java/com/padaks/todaktodak/untact/domain/Room.java
reservation/src/main/java/com/padaks/todaktodak/untact/domain/WebSocketMessage.java
reservation/src/main/java/com/padaks/todaktodak/untact/dto/RoomRequest.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/RoomService.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/UntactService.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java
reservation/src/main/java/com/padaks/todaktodak/untact/util/Parser.java
reservation/src/main/resources/application-dev.yml

- webrtc 테스트용 코드 작성
Feat/is 38

Feat/is 38: webrtc 테스트용 코드 작성

---

reservation/src/main/java/com/padaks/todaktodak/untact/domain/Room.java

Feat/IS-39: 직렬화 에러 수정

---

community/src/main/java/com/padaks/todaktodak/comment/controller/CommontController.java
community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
community/src/main/java/com/padaks/todaktodak/comment/dto/CommentUpdateReqDto.java
community/src/main/java/com/padaks/todaktodak/comment/repository/CommentRepository.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/common/config/RedisConfigs.java
community/src/main/java/com/padaks/todaktodak/communitynotification/controller/SseController.java
community/src/main/java/com/padaks/todaktodak/communitynotification/domain/Notification.java
community/src/main/java/com/padaks/todaktodak/communitynotification/dto/NotificationListDto.java
community/src/main/java/com/padaks/todaktodak/communitynotification/service/NotificationService.java
community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
reservation/gradle/eureka/src/main/resources/application.yml

답변 생성
post별 답변 리스트 조회
의사별(작성자별) 답변 리스트 조회
답변 생성
답변 생성 후 db조회
post별 답변 리스트 조회
1번 post 답변 조회
2번 post 답변 조회
의사별(작성자별) 답변 리스트 조회
IS-36

IS-36/ feat: comment 생성, 조회

---

community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java

답글에 대한 답글 생성
post detail에서 대댓글 조회 가능
대댓글 작성전 db 조회 결과
대댓글 작성 후 db 조회 결과
feat/IS-40

IS-40feat: 대댓글

---

hospital/build.gradle
hospital/src/main/java/com/padaks/todaktodak/HospitalApplication.java
hospital/src/main/java/com/padaks/todaktodak/common/enumdir/DayOfHoliday.java
hospital/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
hospital/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDTO/HospitalListResDto.java
hospital/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
hospital/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
hospital/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
member/src/main/java/com/padaks/todaktodak/MemberApplication.java

- request param : 동, 사용자 위도, 경도 
- 사용자가 지정한 ~~동 기준으로 병원 리스트 조회(ex. 성수동 -> 성수동에 있는 병원만 조회됨)
- 사용자 위도,경도 기반으로 병원까지의 거리 계산
- 오늘날짜에 해당하는 요일의 병원영업시간만 return (ex. 오늘 월요일 -> 월요일 스케쥴만 return) 
- 오늘날짜에 해당하는 요일에 병원 영업시간이 없을 경우 "휴무" return
- 실시간 대기자 수 : 레디스 붙인 이후에 DTO 조립할 예정
**성수동 검색 : 성수동에 있는 병원정보만 뜲, 오늘 요일에 해당하는 스케쥴만 뜲**
**휴무일 경우 아래와 같이 "휴무"라고 뜲**
---
**화양동 검색 : 화양동에 있는 병원정보만 뜲**
feat/IS-32

feat/IS-32 : 병원List조회 api 구현

---

hospital/build.gradle
hospital/src/main/java/com/padaks/todaktodak/HospitalApplication.java

- chore : Hospital 유레카 클라이언트 부분 주석처리
- 유레카 클라이언트 주석처리된 것 모르고 해제하고 main에 머지해버려서 다시 유레카 클라이언트 부분 주석처리하고 올립니다..

chore : Hospital 유레카 클라이언트 부분 주석처리

---

member/src/main/java/com/padaks/todaktodak/MemberApplication.java

chore : Member도 eureka client 주석처리

chore : Member도 eureka client 주석처리

---

reservation/src/main/java/com/padaks/todaktodak/untact/config/WebSocketConfig.java

Feat/IS-39: websocket 메시지 최대 크기 설정 변경

---

reservation/src/main/java/com/padaks/todaktodak/ReservationApplication.java

Feat/IS-47: websocket 설정

---

reservation/src/main/java/com/padaks/todaktodak/hospital/domain/Hospital.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/resources/application-dev.yml

- MSA 합쳐놓고 fk 안이어줬었음
- Hospital 엔티티, Reservation 엔티티 fk로 연결

feat/IS-49 : fix : Hospital 엔티티, Reservation 엔티티 fk로 연결

---

member/.gitignore
member/src/main/java/com/padaks/todaktodak/notification/controller/NotificationController.java
member/src/main/java/com/padaks/todaktodak/notification/domain/Notification.java
member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationReqDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationService.java
member/src/main/resources/application-dev.yml
member/src/main/resources/application.yml

Feat/IS-48: 알림 crud 기능 생성

---

community/.gitignore
community/Dockerfile
community/src/main/resources/application-dev.yml
community/src/main/resources/application.yml

- community Dockerfile 생성 및 application 분리
Feat/IS-51

Feat/IS-51: community Dockerfile 생성 및 application 분리

---

eureka/Dockerfile
gateway/Dockerfile

- eureka, gateway Dockerfile 작성
Feat/IS-47

Feat/IS-47: eureka, gateway Dockerfile 작성

---

member/src/main/java/com/padaks/todaktodak/member/dto/DoctorUpdateReqdto.java

IS-52 fix : DoctorUpdateReqdto 다시 생성

---

member/src/main/java/com/padaks/todaktodak/common/domain/BaseTimeEntity.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/controller/DoctorOperatingHoursController.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursResDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursSimpleResDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java

IS-56 feat:의사 근무시간 생성

---

member/src/main/java/com/padaks/todaktodak/chatmessage/domain/ChatMessage.java
member/src/main/java/com/padaks/todaktodak/chatroom/domain/ChatRoom.java
member/src/main/java/com/padaks/todaktodak/cs/domain/Cs.java
reservation/src/main/java/com/padaks/todaktodak/configs/JwtAuthFilter.java

- chatroom, chat message, cs 엔티티 수정

feat/IS-49 fix : ChatRoom, ChatMessage, Cs엔티티 수정

---

gateway/src/main/resources/application-dev.yml
gateway/src/main/resources/application-local.yml

- gateway websocket routing 설정
Feat/is 65

Feat/is 65: gateway websocket routing 설정

---

reservation/src/main/java/com/padaks/todaktodak/common/config/CorsConfig.java

fix: cors 에 도메인 추가

---

gateway/src/main/resources/application-dev.yml

fix: cors 에 도메인 추가..

---

reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java

- 진료비 병원에서 받아오는 로직 추가
Feat/IS-77

Feat/IS-77: 진료비 병원에서 받아오는 로직 추가

---

member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java

알림 전송시 db에 저장
Postman 알림 전송
DB 저장 내역
feat/IS-78

IS-78 feat: 알림 db 저장 성공

---

reservation/.gitignore
reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/common/config/FirebaseConfig.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/Message.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java

- firebase realtime DB 연결
member에 있는 firebase json 파일 똑같이 reservation/resources에 복붙해주셔야합니다 !!!!!!!
Feat/IS-81

Feat/IS-81: firebase realtime DB 연결

---

member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
member/src/main/java/com/padaks/todaktodak/child/domain/Child.java
member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java

Feat/IS-85: 자녀 프로필 사진 등록

---

eureka/src/main/resources/application.yml
gateway/src/main/resources/application.yml
member/build.gradle
member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentFailDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentSuccessDto.java
member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
member/src/main/resources/application-dev.yml
member/src/main/resources/application.yml
reservation/build.gradle
reservation/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
reservation/src/main/java/com/padaks/todaktodak/common/kafka/KafkaProducerConfig.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationConsumerConfig.java
reservation/src/main/resources/application-dev.yml
reservation/src/main/resources/application.yml

결제 서비스에 카프카를 붙여 알림을 받을 수 있도록 설정
알림을 보낼 객체까지 만드는 과정 완료
추후 알림 파트에서 해당 dto 활용하여 알림 보내주는 로직 추가 필요
아래와 같은 양식으로
결제 성공, 결제 취소, 요청 실패 등을 객체로 변환하였음
feat/IS-80

feat: 결제서비스 + 카프카 붙여서 알림 로직 설정

---

reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/WaitingTurnDto.java

- WaitingTurnDto로 대기열 인원 업데이트
Feat/IS-87

Feat/IS-87: WaitingTurnDto로 대기열 인원 업데이트

---

member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
member/src/main/java/com/padaks/todaktodak/common/kafka/KafkaProducerConfig.java

Feat/IS-88: 자녀 공유시 알림 kafka

---

member/src/main/java/com/padaks/todaktodak/common/service/InitialDataLoader.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/AdminSaveDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberFindPasswordDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/PasswordResetDto.java
member/src/main/java/com/padaks/todaktodak/member/service/CustomOAuth2UserService.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
member/src/main/resources/application.yml
reservation/src/main/resources/application.yml

카카오 회원가입
회원 정보 수정
의사 이메일 인증
의사 아이디(이메일 찾기)
비밀번호 재설정 링크 전송 및 재설정
- 카카오 로그인시 변경되지 않은 회원
- 회원 정보를 올바르게 수정하지 않은 경우
- 회원 정보를 올바르게 수정한 경우
- 의사 아이디 찾기
- 비밀번호 재설정 링크 전송 및 재설정
feat/IS-89

FE: 회원 로그인, 카카오 로그인, 의사 이메일 찾기, 의사 로그인, 비밀번호 재설정 링크 전송 및 재설정 

---

eureka/src/main/resources/application.yml
gateway/src/main/resources/application.yml
member/src/main/java/com/padaks/todaktodak/member/dto/MemberSaveReqDto.java
member/src/main/resources/application.yml
reservation/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/ReservationExceptionType.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/KafkaReservationProducerConfig.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationKafkaConsumer.java

- Listener : containerFactory 수정
- Offset Commit 수동으로 커밋동작
- reservationSchedule 토픽의 파티션 24개로 수정
- 당일예약, 스케줄예약 파라미터 수정, 사용하지 않는 메서드 삭제, 당일예약 메서드 명 수정

Fix/is 100 Reservation 예약 Consumer , ProducerConfig 수정

---

community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/common/feign/MemberFeignClient.java
community/src/main/java/com/padaks/todaktodak/report/controller/ReportController.java
community/src/main/java/com/padaks/todaktodak/report/dto/ReportSaveReqDto.java
community/src/main/java/com/padaks/todaktodak/report/service/ReportService.java
community/src/main/resources/application.yml
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

- 신고시 신고 카운트 기능 구현
Feat/IS-102

Feat/IS-102: 신고시 신고 카운트 기능 구현

---

member/src/main/java/com/padaks/todaktodak/chat/chatroom/dto/ChatRoomListResDto.java
member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
member/src/main/java/com/padaks/todaktodak/chat/cs/domain/CsStatus.java
member/src/main/java/com/padaks/todaktodak/chat/cs/dto/CsResDto.java
member/src/main/java/com/padaks/todaktodak/chat/cs/service/CsService.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/CreateReviewReqDto.java

- pr내용 이전과 동일합니다
- 변경사항 커밋안하고 머지해버려서 다시올립니다...

feat/IS-92 fix : CS 관련 crud 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/exception/exceptionType/GlobalExceptionType.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationKafkaConsumer.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

Fix/is 108 예약 탭 Kafka 제거.... ㅠㅠ

---

member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

fix : 노쇼 카운트 5회 이상 시 멤버 탈퇴 처리

---

community/src/main/java/com/padaks/todaktodak/comment/repository/CommentRepository.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
community/src/main/java/com/padaks/todaktodak/post/repository/PostRepository.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java

커뮤니티 답변 권한관리
삭제 권한관리
게시글/답변 삭제 후 리스트 조회 불가 (deletedAt으로 수정)
##답변 권한 수정
게시글 본인 답변
게시글 본인 답변 db 저장
게시글 일반인 답변 불가
게시글 의사 답변
게시글 의사 답변 db저장
게시글 일반인 다시답변 불가
원래 게시글 리스트
게시글 삭제
게시글 삭제후 리스트 조회
다른 작성자의 댓글 삭제 불가
본인 댓글 삭제
댓글 삭제 전 게시글 상세 조회
댓글 삭제후 게시글 상세 조회
IS-110

feat/IS-110 fix : 커뮤니티 답변 권한관리, 삭제 권한관리, 게시글/답변 삭제 후 리스트 조회 불가

---

member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/PaymentCancelFailDto.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java

결제 알림 완료
기존 커뮤니티 알림 로직을 수정 완료
memberId 에서 memberEmail로 받도록 수정
feat/IS-112

feat: 결제 알림 및 커뮤니티 알림 로직 수정 및 memberEmail 코드로 변경

---

reservation/src/main/java/com/padaks/todaktodak/common/config/RedisConfig.java
reservation/src/main/java/com/padaks/todaktodak/untact/domain/WebSocketMessage.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/RedisPublisher.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/RoomService.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

- 메시지 pub/sub으로 변환
Feat/IS-106

Feat/IS-106: 메시지 pub/sub으로 변환

---

community/src/main/java/com/padaks/todaktodak/comment/controller/CommentController.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberPayDto.java

신고 5회 회원 게시글 작성, 수정, 삭제 불가
신고 5회 게시글 작성 불가
신고 5회 게시글 수정 불가
신고 5회 게시글 삭제 불가
신고 5회 답변 작성 불가
신고 5회 답변 수정 불가
신고 5회 답변 삭제 불가
feat/IS-114

Feat/is-114 신고5회 커뮤니티 사용제한

---

member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
member/src/main/java/com/padaks/todaktodak/childparentsrelationship/domain/ChildParentsRelationship.java
member/src/main/java/com/padaks/todaktodak/childparentsrelationship/repository/ChildParentsRelationshipRepository.java
member/src/main/java/com/padaks/todaktodak/common/exception/MemberExceptionHandler.java

- 자녀 deleteAtIsNull처리
Feat/IS-117

Feat/IS-117: 자녀 deleteAtIsNull

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java

의사 근무시간 중복 등록 방지
이미 등록된 요일에 추가 등록 불가
기존 의사 근무시간
fix/IS-118

IS-118 fix : 의사 근무시간 중복 등록 방지 변경

---

member/src/main/java/com/padaks/todaktodak/chat/service/ChatKafkaListener.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
member/src/main/java/com/padaks/todaktodak/notification/domain/Type.java

채팅방 내 내용 입력시 상대방에게 fcm 알림 전송
채팅방 생성시 관리자에게 fcm 알림 
관리자가 받는 알림
사용자가 받는 알림
상대방이 채팅방에 없을 경우 알림 보내는것으로 수정 필요
IS-119

feat/IS-119feat: 채팅 메세지 전송시 상대방에게 알림 전송

---

member/src/main/java/com/padaks/todaktodak/common/kafka/ReservationKafkaConsumerConfig.java
member/src/main/java/com/padaks/todaktodak/notification/dto/ReservationSuccessResDto.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

1. 당일 예약, 스케줄 예약 성공 및 실패 시 적절한 Kafka 토픽에 메시지 전송
2. Kafka 메시지 수신 시 사용자에게 적절한 알림을 전송. (미구현)
- 스케줄 예약 성공시 Kafka 에 메시지 적재
- 당일 예약 성공 시 Kafka 에 메시지 적재
- 스케줄 예약 성공 시 병원 관리자에게 알림 전송
- 당일 예약 성공 시 병원 관리자에게 알림 전송 (미구현)
close #140

#140 feat : 당일 예약, 스케줄 예약 성공 및 실패 시 알람 설정(알람 미구현)

---

member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
member/src/main/java/com/padaks/todaktodak/child/domain/Child.java
member/src/main/java/com/padaks/todaktodak/child/dto/ChildResDto.java
member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java

- 자녀 반환 값에 이미지 포함 시키기
- 자녀 수정시 이미지도 변경 가능하도록 수정
Feat/IS-125

Feat/IS-125: 자녀 이미지 반환 및 변경 코드 수정

---

reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewMyListResDto.java
reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

feat: 나의 리뷰 리스트

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/controller/DoctorOperatingHoursController.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursSimpleResDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java

의사 근무시간 등록, 수정, 삭제 수정
의사 근무시간 생성 
의사 근무시간 생성 - 권한 관리
의사 근무시간 수정
의사 근무시간 수정 - 권한 관리 
의사 근무시간 삭제
ub.com/user-attachments/assets/d6f98e59-064d-4e3b-8296-3c0ca70eabcb">
의사 근무시간 삭제 - 권한 관리 
fix/IS-126

Fix/IS-126 의사 근무 시간 설정 수정

---

member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewMyListResDto.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

deletedAtNull인것만 보이도록 로직 수정
feat/IS-129

feat: myReviewList deletedAtNull

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

- [x ] 기능 추가
병원별 의사 목록 조회
fix/IS-130

feat/IS-130/feat: 병원별 의사 목록 조회

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

병원별 의사 목록 조회 : 의사 약력, 근무시간 추가
feat/IS-130

Revert "feat/IS-130/feat: 병원별 의사 목록 조회"

---

member/src/main/java/com/padaks/todaktodak/chat/service/ChatKafkaListener.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
member/src/main/java/com/padaks/todaktodak/member/controller/FcmController.java
member/src/main/java/com/padaks/todaktodak/member/repository/DelMemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/FcmService.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java

findByRoleAndHospitalId 추가
Feat/is-133

Feat/is 133 findByRoleAndHospitalId 추가

---

reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
reservation/src/main/java/com/padaks/todaktodak/review/domain/Review.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewListResDto.java
reservation/src/main/java/com/padaks/todaktodak/review/dto/ReviewSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

의사별 대면+ 비대면 리뷰 목록
대면 리뷰 목록
비대면 리뷰 목록
리뷰 디테일 
대면 + 비대면
대면 + 이름 마스킹 처리
비대면
의사 리뷰 디테일
feat/IS-138

feat: 의사별 대면&&비대면, 대면, 비대면, 리뷰디테일 추가 + 리뷰 작성자 이름 마스킹 처리

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java

IS-136/fix: doctorListByHospital 추가

---

community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignNameDto.java
community/src/main/java/com/padaks/todaktodak/common/feign/MemberFeignClient.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberFeignNameDto.java

Fix/is-139 게시판 사용자 이름 정보 추가

---

community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

feat: 커뮤니티 사용자 마스킹 처리, feign dto 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

feat: 회원 사진 업데이트

---

community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java

commentList 부모 comment 정보, 생성/수정시간 추가
fix/IS-139

fix/IS-139 fix: commentList 부모 comment 정보, 생성/수정시간 추가

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationSaveReqDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

1. 진료 예약 로직 수정
2. 해당 의사별 예약 시간 출력 로직 구현

fix:  진료 예약 로직 수정

---

member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java

- 자녀 등록 혹은 변경시에 이미지 기본으로 들어가도록 설정
Fix/is-150

Fix/is-150: 자녀 이미지 변경 코드 수정

---

member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/DoctorTimeRequestDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

해당 병원 의사 목록에 email 추가, 해당 일자의 의사 예약 시간 가져오는 로직 구현

fix : 해당 병원 의사 목록에 email 추가, 해당 일자의 의사 예약 시간 가져오는 로직 구현

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

Feat/is-152: 회원 검색 기능 구현

---

reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/RedisPublisher.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

- medichart 중복 생성 안되도록 코드 변경
Feat/is 162

Feat/is 162: medichart 중복 생성 안되도록 코드 변경

---

community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostListDto.java

PostList postImgUrl 추가
feat/IS-165

feat/IS-165 fix: PostList postImgUrl 추가

---

community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/repository/PostRepository.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java

나의 게시글 목록
1번 유저 로그인
2번 유저 로그인
feat/IS-167

feat: 나의 게시글 목록

---

reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

- 비대면 채팅을 pub/sub 구조로 바꾸면서 누락된 부분이 있어서 수정했습니다 !
Fix/is-169

Fix/is-169: 비대면 채팅 종료 로직 수정

---

reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalDetailResDto.java
reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalListResDto.java

- 병원 crud 관련 response dto 필드 추가했습니다.
Feat/is 142

Feat/is 142 : 병원관련 dto 필드 수정

---

community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java

예약리스트 requestParam 변경
기존 -> requestBody
feat/IS-177

feat: 캘린더 데이터를 위한 예약 리스트

---

community/src/main/java/com/padaks/todaktodak/report/controller/ReportController.java
community/src/main/java/com/padaks/todaktodak/report/domain/Report.java
community/src/main/java/com/padaks/todaktodak/report/domain/Status.java
community/src/main/java/com/padaks/todaktodak/report/dto/ReportListResDto.java
community/src/main/java/com/padaks/todaktodak/report/dto/ReportSaveReqDto.java
community/src/main/java/com/padaks/todaktodak/report/service/ReportService.java

Feat/IS-175: 신고 처리 상태 추가

---

community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
member/src/main/java/com/padaks/todaktodak/common/dto/CheckHospitalListReservationReqDto.java
member/src/main/java/com/padaks/todaktodak/common/dto/DoctorInfoDto.java
member/src/main/java/com/padaks/todaktodak/common/dto/HospitalInfoDto.java
member/src/main/java/com/padaks/todaktodak/common/dto/ReviewDetailDto.java
member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/ReservationFeignDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/ReviewListResDto.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/dto/CheckHospitalListReservationReqDto.java
reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalInfoDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationFeignDto.java

의사 정보 : 의사 이름, 사진, 병원 명, 예약수, 리뷰수 조회
Feat/IS-172

Feat/is 172  의사 정보 : 의사 이름, 사진, 병원 명, 예약수, 리뷰수 조회

---

member/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ChildResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/TodayReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
reservation/src/main/java/com/padaks/todaktodak/review/repository/ReviewRepository.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

- 오늘 예약 리스트 조회
- 이전 예약 리스트 조회
- 예약에 대한 리뷰 존재 여부
- 오늘 예약
- 이전 예약
- 리뷰 확인 
postman request가 안만들어져서 패스~ 프론트 pr 에서 확인해주세요

Fix/is 153 예약에 대한 리뷰 존재 여부 api, 오늘 예약-이전 예약 리스트 호출 api 작성

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/TodayReservationResDto.java

- [] 기능 추가
dtoMapper 수정, 오늘-이전 예약 리스트에 예약 id 추가

fix : dtoMapper 수정, 오늘-이전 예약 리스트에 예약 id 추가

---

community/src/main/java/com/padaks/todaktodak/post/service/PostService.java

커뮤니티 사진 없이 게시글 등록 가능
FIX/IS-185

FIX/IS-185 fix: 커뮤니티 사진 없이 게시글 등록 가능

---

member/src/main/java/com/padaks/todaktodak/member/dto/DoctorResDto.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckListChildReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckListReservationReqDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/DoctorResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

예약 리스트 조회 기능 타입별로 변경, 아이별 예약 리스트 조회 기능 구현
- 예약 all
- 예약 Scheduled
- 예약 Immediate
- 예약 아이별
- 앤 예약 내역이 없어서 빈배열

fix : 예약 리스트 조회 기능 타입별로 변경, 아이별 예약 리스트 조회 기능 구현

---

member/src/main/java/com/padaks/todaktodak/event/controller/EventController.java
member/src/main/java/com/padaks/todaktodak/event/domain/Event.java
member/src/main/java/com/padaks/todaktodak/event/domain/Type.java
member/src/main/java/com/padaks/todaktodak/event/dto/EventCreateReqDto.java
member/src/main/java/com/padaks/todaktodak/event/dto/EventDetailResDto.java
member/src/main/java/com/padaks/todaktodak/event/dto/EventListResDto.java
member/src/main/java/com/padaks/todaktodak/event/dto/EventUpdateReqDto.java
member/src/main/java/com/padaks/todaktodak/event/repository/EventRepository.java
member/src/main/java/com/padaks/todaktodak/event/service/EventService.java

feat: 캘린더를 위한 백엔드 작업 event 테이블 추가

---

member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ReservationSaveResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

- 의료 정보 api 받아오기
비대면 진료 데이터 "진-짜"로 받아왔습니다
Feat/IS-188

Feat/IS-188: 의료 정보 api 받아오기

---

member/src/main/java/com/padaks/todaktodak/event/domain/Event.java
member/src/main/java/com/padaks/todaktodak/event/domain/Type.java
member/src/main/java/com/padaks/todaktodak/event/service/EventService.java

feat: 캘린더 작업을 위한 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ComesReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationHistoryRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

오는 예약 (오늘을 포함한 오는 예약), 지난 예약으로 설정되도록
취소된 예약 내역도 가져옴.

fix : 오는 예약, 지난 예약으로 설정, 취소된 예약 내역도 가져오도록 변경

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/ReservationHistory.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ComesReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

fix : 예약 리스트 호출 로직 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationReqDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

- 요청 파람 형식으로 변환
- 요청 파람에 date 추가
- 반환 값에 이름, 자녀 정보 추가
- dto mapper 수정
Feat/IS-205

Feat/IS-205: 병원 측 예약리스트 api 수정

---

community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/post/domain/Post.java

Fix/is 189 커뮤니티 세부사항 조정

---

member/build.gradle
member/src/main/java/com/padaks/todaktodak/event/controller/EventController.java
member/src/main/java/com/padaks/todaktodak/event/controller/GoogleCalendarProxyController.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

캘린더에 공휴일을 불러드리기 위한 백엔드 api추가
feat/IS-194

feat: 캘린더 구글 공휴일 api, rservation 이슈 있을지도..?

---

member/src/main/java/com/padaks/todaktodak/event/controller/GoogleCalendarProxyController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/domain/Reservation.java

구글 맵 api key 재발급 및 숨김 처리
feat/IS-209

chore: 구글 맵 api key 재발급 및 숨김 처리

---

reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckHospitalListReservationResDto.java

- [res dto 예약 id 추가](https://github.com/Todak-Padak/TodakTodak_backend/commit/c36faa555156a48062dee0ffa7028b7afb1872f9)
fix/is-213

fix/is-213: res dto 예약 id 추가

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/WaitingTurnDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

firebase Realtime Database 에 적재 시 병원별 , 의사별 적재로 수정 
데이터 삭제시 그 다음 값의 수 변경
- 데이터 적재
- 67번 예약 접수 시
- 71번 예약 취소 시

Fix/is 206 Firebase Realtime Database 적재 로직 수정

---

member/src/main/java/com/padaks/todaktodak/child/domain/Child.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
member/src/main/java/com/padaks/todaktodak/notification/domain/FcmNotification.java
member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

알림 리다이렉트 url  수정 및 카프카 ack 처리
feat.IS-212

feat: 알림 url 수정 및 카프카 ack 처리

---

member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorDetailDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorInfoDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/HospitalInfoDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/ReviewDetailDto.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/dto/HospitalInfoDto.java

- 의사 디테일 api 생성
- 병원 dto 수정
feat/is-214

feat/is-214: 의사 디테일 api 생성

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberListResDto.java
member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
member/src/main/java/com/padaks/todaktodak/notification/domain/FcmNotification.java
member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationReqDto.java
member/src/main/java/com/padaks/todaktodak/notification/dto/NotificationResDto.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java

알림 타이틀 바디 분리
알림 페이지네이션
자잘한 수정
feat/IS-216

feat: 알림 페이지네이션,title body 분리 및 자잘한 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

Feat/IS-222: 내가 속한 병원이름 가져오기

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

fix/is-222: 비대면 의사 리스트 수정!!!

---

community/src/main/java/com/padaks/todaktodak/comment/controller/CommentController.java
community/src/main/java/com/padaks/todaktodak/comment/domain/Comment.java
community/src/main/java/com/padaks/todaktodak/comment/dto/CommentSaveDto.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/common/dto/HospitalNameFeignDto.java
community/src/main/java/com/padaks/todaktodak/common/dto/MemberFeignDto.java
community/src/main/java/com/padaks/todaktodak/common/dto/MemberInfoDto.java
community/src/main/java/com/padaks/todaktodak/common/feign/HospitalFeignClient.java
community/src/main/java/com/padaks/todaktodak/post/domain/Post.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostDetailDto.java
community/src/main/java/com/padaks/todaktodak/post/dto/PostsaveDto.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberInfoDto.java
reservation/src/main/java/com/padaks/todaktodak/common/dto/HospitalNameFeignDto.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/CheckListReservationReqDto.java

커뮤니티 게시글 작성, 작성자 사진
커뮤니티 댓글 작성 작성자 사진, 병원이름
게시글 조회시 댓글 조회 - 내용 삭제
post별 commentList 조회
Fix/IS-207

Fix/IS-207 커뮤니티 게시글 작성, 댓글 작성 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/dto/DtoMapper.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/dto/ComesReservationResDto.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

fix : 오늘 예약 리스트에 doctorId 추가

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberListResDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

- 프론트 멤버 정렬과 검색을 위한 수정
feat/IS-220

feat: 멤버리스트 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

- 병원 인기쟁이 api
- 의사 인기쟁이 api
Feat/is 231

Feat/is-231: 인기쟁이 api

---

community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/repository/PostRepository.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

feat/IS-234: 인기쟁이 post

---

reservation/src/main/java/com/padaks/todaktodak/hospital/adminDto/AdminHospitalListDetailResDto.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

관리자
- 병원 리스트
- 병원 디테일
- 병원 페이지네이션
- 병원 필터링
feat/IS-233

feat: 관리자 병원 페이지를 위한 백엔드 작업

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorDeleteDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorListResDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

병원 관리자 의사 삭제
병원별 의사목록, 삭제된 의사 조회 불가
의사 리스트 조회, 인증 여부 추가
병원 관리자 의사 삭제
병원별 의사목록, 삭제된 의사 조회 불가
의사 리스트 조회, 인증 여부 추가
Feat/IS-241

Feat/IS-241 병원 관리자 의사 삭제 | 병원별 의사목록, 삭제된 의사 조회 불가 | 의사 리스트 조회, 인증 여부 추가

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursResDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/DoctorUntactListDto.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

- param으로 받은 기준으로 정렬 구현
- param으로 받은 searchQuery 로 검색 구현
- 의사 운영 시간도 반환 값에 포함
Feat/is 240

Feat/is 240: 비대면 의사 검색, 정렬 구현

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/domain/Role.java
member/src/main/java/com/padaks/todaktodak/member/dto/HospitalAdminSaveReqDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberDetailResDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberResDetailDto.java
member/src/main/java/com/padaks/todaktodak/member/dto/PaymentSuccessDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/common/domain/Role.java
reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java

- role 추가
- 정기결제시 병원 관리자 role update
- role update 동시에 새로운 토큰 발급해서 프론트에 반환
- 해당 멤버는 해당 토큰으로 로컬스토리지에 토큰을 다시 set
병원어드민 생성하는 로직 수정 필요 (deltedAt + isVerfied 설정)
feat/IS-251

feat: 정기결제 및 병원 관리자 role 추가, 새로운 토큰 발급 및 갱신

---

reservation/src/main/java/com/padaks/todaktodak/review/controller/ReviewController.java
reservation/src/main/java/com/padaks/todaktodak/review/service/ReviewService.java

feat: 의사 비대면 리스트 평균 평점

---

member/src/main/java/com/padaks/todaktodak/common/enumdir/DayOfHoliday.java
member/src/main/java/com/padaks/todaktodak/common/feign/ReservationFeignClient.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/domain/DoctorOperatingHours.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursReqDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursResDto.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
member/src/main/java/com/padaks/todaktodak/member/dto/HospitalOperatingHoursResDto.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java

의사 휴게시간 병원 휴게시간으로 자동설정
fix/IS-260

fix/IS-260 fix: 의사 휴게시간 병원 휴게시간으로 자동설정

---

reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

- 의사 예약 중 비대면 여부에 따라 예약 가져오는 api 생성
feat/IS-249

feat/IS-249: 비대면 의사 예약 리스트 new

---

reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

fix: 비대면 의사 예약 리스트 res 수정

---

reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
reservation/src/main/java/com/padaks/todaktodak/payment/repository/PaymentRepository.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java

feat: 결제 리스트(검색, 필터링)

---

member/src/main/java/com/padaks/todaktodak/chat/cs/controller/CsController.java
member/src/main/java/com/padaks/todaktodak/chat/cs/domain/Cs.java
member/src/main/java/com/padaks/todaktodak/chat/cs/dto/CsListResDto.java
member/src/main/java/com/padaks/todaktodak/chat/cs/repository/CsRepository.java
member/src/main/java/com/padaks/todaktodak/chat/cs/service/CsService.java

feat: cs 리스트 검색 및 필터링

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/dto/MontlyMemberCountDto.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java

feat: 토닥 admin 관리자 페이지에 필요한 api 작성

---

reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java

fix : 총 매출 구하는 로직 추가

---

member/src/main/java/com/padaks/todaktodak/chat/chatmessage/dto/ChatMessageResDto.java
member/src/main/java/com/padaks/todaktodak/chat/chatroom/dto/ChatRoomListResDto.java
member/src/main/java/com/padaks/todaktodak/chat/chatroom/repository/ChatRoomRepository.java
member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
member/src/main/java/com/padaks/todaktodak/chat/cs/domain/Cs.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
member/src/main/java/com/padaks/todaktodak/common/service/InitialDataLoader.java
member/src/main/java/com/padaks/todaktodak/member/dto/AdminSaveDto.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/service/HospitalOperatingHoursService.java

- 병원영업시간 수정 시 요일중복등록 불가 예외로직 추가
Fix/is 269

Fix/is 269 : 채팅리스트 pageable 로 수정, 병원영업시간 요일중복등록 불가 예외로직 추가

---

reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/repository/HospitalOperatingHoursRepository.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/service/HospitalOperatingHoursService.java

feat: 병원어드민 영업시간관리 백엔드

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/repository/DoctorOperatingHoursRepository.java
member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java

Fix/IS-291: 의사 api 수정

---

member/src/main/java/com/padaks/todaktodak/chat/chatroom/dto/CsMemberResDto.java
member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java

채팅방 Id 를 통한 멤버 정보 검색 API 구현

---

member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

1. 미사용 API 삭제
2. 미승인 병원 개수 조회 API 구현

Feat/is 305 미승인 병원 개수 조회 API 구현

---

reservation/src/main/java/com/padaks/todaktodak/medicalchart/repository/MedicalChartRepository.java
reservation/src/main/java/com/padaks/todaktodak/medicalchart/service/MedicalChartService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationAdminController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationAdminService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

- 진료내역 상태 업데이트 코드 수정 
Feat/is 309

Feat/is 309: 진료내역 수정

---

member/src/main/java/com/padaks/todaktodak/chat/chatmessage/dto/ChatMessageReqDto.java
member/src/main/java/com/padaks/todaktodak/chat/chatmessage/dto/ChatMessageResDto.java
member/src/main/java/com/padaks/todaktodak/chat/chatroom/dto/ChatRoomMemberInfoResDto.java
member/src/main/java/com/padaks/todaktodak/chat/controller/ChatController.java
member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/controller/HospitalOperatingHoursController.java
reservation/src/main/java/com/padaks/todaktodak/hospitaloperatinghours/service/HospitalOperatingHoursService.java

- 채팅메시지리스트 dto에 sender id 추가
- 채팅방에 참여한 회원정보 조회하는 api 추가
- WebSocketService에 sendMessage 수정 (request dto 필드 추가)
(request dto 필드 추가)
feat/IS-286

feat/IS-286 : 채팅관련 로직 수정 

---

member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
member/src/main/java/com/padaks/todaktodak/notification/service/PaymentEventListener.java

알림 내용 변경과 타겟 url 수정
feat/IS-312

feat: 알림 내용 변경, typeUrl 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java

- 병원 어드민이 의사 프로필 사진 변경할 수 있도록 수정
fix/IS-316

fix/IS-316: 의사 프로필 사진 변경

---

reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

병원어드민 병원리스트 deletedAtIsNull 처리
feat/IS-312

feat: 병원어드민 병원리스트 deletedAtIsNull처리

---

member/src/main/java/com/padaks/todaktodak/member/repository/MemberRepository.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

fix : 삭제된 의사 리스트 조회 안되게 API 수정

---

member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java
reservation/src/main/java/com/padaks/todaktodak/common/domain/Role.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

fix : 노쇼 스케줄러 동작 시 이미 Noshow 인 경우 제외, 지난 예약 Pageable 제외

---

reservation/src/main/java/com/padaks/todaktodak/medicalchart/controller/MedicalChartController.java
reservation/src/main/java/com/padaks/todaktodak/untact/controller/UntactController.java

Feat/IS-323: 권한관리 hasRole 추가

---

member/src/main/java/com/padaks/todaktodak/child/controller/ChildController.java
member/src/main/java/com/padaks/todaktodak/childparentsrelationship/service/ChildParentsRelationshipService.java
member/src/main/java/com/padaks/todaktodak/common/exception/MemberExceptionHandler.java

Feat/IS-329: 자녀 공유 에러처리

---

community/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
community/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
member/src/main/java/com/padaks/todaktodak/member/Handler/OAuth2SuccessHandler.java
member/src/main/java/com/padaks/todaktodak/member/service/OAuthAttributes.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
reservation/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
reservation/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java

feat: 권한 제어

---

member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
reservation/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java

fix/IS-334: 웹소켓 권한 처리

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/service/DoctorOperatingHoursService.java

- 의사 근무시간과 병원 운영시간 비교 로직 추가
fix/IS-337

fix/IS-337: 의사 근무시간과 병원 운영시간 비교 로직 추가

---

README.md

Docs/is 326 readme 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

feat: 토닥/병원 관계자 로그인 분리 및 예외 처리 구체화

feat: 토닥/병원 관계자 로그인 분리 및 예외 처리 구체화

---

reservation/src/main/java/com/padaks/todaktodak/reservation/controller/ReservationController.java
reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

fix : 당일 예약에 한 병원 똑같은 자녀 예약 불가로 수정

---

member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java

fix : 예약 알람 내용 수정

---

member/src/main/java/com/padaks/todaktodak/doctoroperatinghours/dto/DoctorOperatingHoursSimpleResDto.java

- 데이터 형식 HH:mm으로 변경
fix/IS-347

fix/IS-347: 근무시간 데이터 형식 변경

---

reservation/src/main/java/com/padaks/todaktodak/common/config/RedisConfig.java
reservation/src/main/java/com/padaks/todaktodak/untact/domain/Room.java
reservation/src/main/java/com/padaks/todaktodak/untact/service/RoomService.java

fix/IS-353: 비대면 채팅방 redis 수정

---

member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java

Fix/is 354 스케줄 예약 알림 문자 수정

---

community/src/main/java/com/padaks/todaktodak/comment/dto/CommentDetailDto.java
community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java

댓글, 대댓글 프로필 사진 보이도록 수정
fix/IS-361

fix/IS-361 fix: 댓글, 대댓글 프로필 사진 보이도록 수정

---

.github/workflows/todak_msa_k8s.yml
community/k8s/community_depl.yml
community/k8s/community_service.yml
community/src/main/resources/application-dev.yml
k8s/ConfigMap.yml
k8s/certificate.yml
k8s/ingress.yml
member/k8s/member_depl.yml
member/k8s/member_service.yml
member/src/main/java/com/padaks/todaktodak/common/config/JwtAuthFilter.java
member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/domain/Member.java
member/src/main/java/com/padaks/todaktodak/member/dto/MemberLoginDto.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java
member/src/main/java/com/padaks/todaktodak/notification/controller/FcmController.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java
member/src/main/resources/application-dev.yml
reservation/k8s/reservation_depl.yml
reservation/k8s/reservation_service.yml
reservation/src/main/resources/application-dev.yml

feat: 알림 수정 및 k8s 배포 스크립트

---

member/src/main/java/com/padaks/todaktodak/common/config/FcmConfig.java
member/src/main/resources/application.yml

feat: fcm이슈

---

reservation/src/main/java/com/padaks/todaktodak/hospital/controller/HospitalController.java
reservation/src/main/java/com/padaks/todaktodak/hospital/repository/HospitalRepository.java
reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

fix: main 코드 적용

---

member/src/main/java/com/padaks/todaktodak/chat/service/ChatService.java

- 채팅방 생성시 fcm에러 발생으로 채팅방 생성이 아예 안되어버리는 이슈 해결을 위해 
try catch 추가했습니다

fix: fcm 에러 처리 수정

---

community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
member/src/main/java/com/padaks/todaktodak/common/kafka/CommunityKafkaConsumerConfig.java
member/src/main/java/com/padaks/todaktodak/notification/service/NotificationKafkaConsumer.java

feat: prod(fcm토큰비동기화)

---

member/build.gradle

feat: redis 삭제 및 결제 비용

---

reservation/src/main/java/com/padaks/todaktodak/untact/service/RoomService.java
reservation/src/main/java/com/padaks/todaktodak/untact/socket/SignalHandler.java

- 멀티 서버끼리 방 정보 공유가 제대로 안되는 것 같아 디버깅하고 있습니다
fix/IS-394

fix/IS-394: 화상채팅 room 초기화 코드 디버깅

---

community/src/main/java/com/padaks/todaktodak/common/config/CorsConfig.java
member/src/main/java/com/padaks/todaktodak/common/config/WebConfig.java
reservation/src/main/java/com/padaks/todaktodak/common/config/CorsConfig.java

feat: front 3000 cors
3000번 로컬호스트 cors 추가

feat: front 3000 cors

---

community/src/main/java/com/padaks/todaktodak/comment/service/CommentService.java

feat: 댓글리스트 이름

---

community/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java
community/src/main/java/com/padaks/todaktodak/post/controller/PostController.java
community/src/main/java/com/padaks/todaktodak/post/service/PostService.java
community/src/main/resources/application.yml

feat: 게시글 좋아요 여부

---

README.md

docs:readme 수정

---

README.md

docs:readme 프로필 사진 수정

---

member/src/main/java/com/padaks/todaktodak/common/config/RedisCacheConfig.java
reservation/src/main/java/com/padaks/todaktodak/common/config/RedisCacheConfig.java

feat: 오브젝트 매퍼

---

member/src/main/java/com/padaks/todaktodak/common/config/RedisCacheConfig.java
member/src/main/java/com/padaks/todaktodak/common/config/RedisConfig.java
reservation/src/main/java/com/padaks/todaktodak/common/config/RedisCacheConfig.java

feat: 빈 충돌

---

member/build.gradle

feat: ses 삭제[

---

member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java

feat: fcm알림 중복 수신 방지

---

member/src/main/java/com/padaks/todaktodak/notification/repository/NotificationRepository.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java

feat: fcm 처리

---

member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java

feat: fcm 중복 메서드 제거
feat: fcm 중복 메서드 제거

feat: fcm 중복 메서드 제거

---

member/src/main/java/com/padaks/todaktodak/member/service/CustomMemberDetailsService.java
member/src/main/java/com/padaks/todaktodak/notification/service/FcmService.java

fcm token 없는 경우 예외 처리
feat/IS-417

FE: 알림 로직 수정

---

reservation/src/main/java/com/padaks/todaktodak/reservation/repository/ReservationRepository.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

fix : 백엔드 지난 예약 GET API 수정

---

README.md

docs/IS-427 docs:readme 시연영상, 배포사이트로 수정

---

README.md

docs:readme 시스템 아키텍쳐 수정
docs/IS-427

docs/IS-427 docs:readme 시스템 아키텍쳐 수정

---

reservation/src/main/java/com/padaks/todaktodak/common/kafka/KafkaConsumerConfig.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/RealTimeKafkaService.java
reservation/src/main/java/com/padaks/todaktodak/reservation/service/ReservationService.java

당일 예약 카프카 붙여보기

---

reservation/src/main/java/com/padaks/todaktodak/common/config/RedisConfig.java
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java

실시간 DB update 로직 수정

---

README.md

docs/IS-430 docs:readme 그라파나 시연영상추가

---

.github/workflows/todak_msa_k8s.yml
reservation/src/main/java/com/padaks/todaktodak/reservation/realtime/RealTimeService.java

Fix/is 423 실시간 DB 수정

---

member/src/main/java/com/padaks/todaktodak/member/controller/MemberController.java
member/src/main/java/com/padaks/todaktodak/member/service/MemberService.java

feat: test로그인 심사를 위한 임시 로그인 기능

feat: test로그인 심사를 위한 임시 로그인 기능

---

.github/workflows/todak_msa_k8s.yml

feat: k8s yml

---

community/k8s/community_depl.yml
k8s/alert-rules.yml
k8s/certificate.yml
k8s/ingress-monitor.yml
k8s/ingress.yml
k8s/prometheus.yml
member/k8s/member_depl.yml
reservation/k8s/reservation_depl.yml

프로메테우스 그라파나를 통한 pods와 node의 cpu, memory 확인 가능
feat/IS-428

feat: 프로메테우스 그라파나 완료

---

member/src/main/java/com/padaks/todaktodak/common/config/SecurityConfig.java

feat: 시큐리티

---

reservation/src/main/java/com/padaks/todaktodak/hospital/service/HospitalService.java

feat: 병원리스트 캐싱처리

---

member/src/main/java/com/padaks/todaktodak/child/service/ChildService.java

fix/IS-434 : 자녀 기본 이미지 변경

---

community/src/main/resources/application-dev.yml
member/k8s/member_depl.yml
member/src/main/resources/application-dev.yml
reservation/k8s/reservation_depl.yml
reservation/src/main/resources/application-dev.yml

feat: cpu 점유율 수정, update문 수정
feat: cpu 점유율 수정, update문 수정
feat/IS-433

feat: cpu 점유율 수정, update문 수정

---

reservation/src/main/java/com/padaks/todaktodak/payment/controller/PaymentController.java
reservation/src/main/java/com/padaks/todaktodak/payment/service/PaymentService.java

feat: 결제금액
